### ISSUE TITLE
'./data/words.txt' not found.

### ISSUE THREAD

**Issue by deepak242424** [m-chanakya/scar#9]
Dear Authors,

I tried running your code and got the error "No such file or directory: './data/words.txt"

I only want to do the inference. Can you please share how to get this file?

Thanks.

**Comment by arjunmanoharan** [comment]
I am facing the same issue. Authors kindly clarify.

**Comment by m-chanakya** [comment]
Updated the README to include the preprocessing steps that need to be run before training the model.
